### ISSUE TITLE
cannot produce the result with backbone of resnet

### ISSUE THREAD

**Issue by encounter7777** [kkakkkka/ETRIS#16]

**Comment by kkakkkka** [comment]
Hello,
﻿
Thank you for your interest in our project. For multi-GPU training, we will be updating faster parallel training code and README instructions in the near future, around January 2025. I've noticed that the experimental results may vary across different machines and environments. Initially, I conducted the experiments using a 40G A100 GPU with Python 3.9 or 3.10. You might be able to reproduce our results by training on a machine with similar specifications.

**Comment by kkakkkka** [comment]
I've just implemented this feature. You can pull the latest code to utilize multi-GPU training.
