### ISSUE TITLE
Cannot reproduce the reported results

### ISSUE THREAD

**Issue by zhiheLu** [kkakkkka/ETRIS#2]
Hi,

Thanks for your great work. 
I ran the code with ResNet-50 on RefCOCO and got the results 69.75/69.07/69.46 on val/test A/test B. The result on test A is much worse than the reported result 73.11.

Could you give some suggestions on this situation?

Many thanks.

**Comment by Mr-Bigworth** [comment]
Hi, I encountered a similar problem during replication of the training process, where the RefCOCO accuracy was observed to be around 69.5% (val). How did you solve it? Thanks!

**Comment by kkakkkka** [comment]
Hi, the weights of our model have been made available at the following link: [https://pan.baidu.com/s/1jaOJKdIg1t8wnWrxgCkkRA?pwd=vmyv](https://pan.baidu.com/s/1jaOJKdIg1t8wnWrxgCkkRA?pwd=vmyv) 
Please note that you may need to enter the password "vmyv" to access the files.

**Comment by kkakkkka** [comment]
> me too,i can't reproduce the report results with GPU 3090,especially in backbone res50

I've noticed that the experimental results may vary across different machines and environments. Initially, I conducted the experiments using a 40G A100 GPU with Python 3.9 or 3.10. You might be able to reproduce our results by training on a machine with similar specifications. In fact, we have also released weights on ViT and Resnet for reproducing the results.

**Comment by Mr-Bigworth** [comment]
> > me too,i can't reproduce the report results with GPU 3090,especially in backbone res50
> 
> I've noticed that the experimental results may vary across different machines and environments. Initially, I conducted the experiments using a 40G A100 GPU with Python 3.9 or 3.10. You might be able to reproduce our results by training on a machine with similar specifications.

Thanks, I'll try it again. Happy new year!

**Comment by kkakkkka** [comment]
> Thanks, I'll try it again. Happy new year!

Happy new year! You can also try our new project [Densely Connected Parameter-Efficient Tuning for Referring Image Segmentation](https://github.com/jiaqihuang01/DETRIS), which has **over 10 IoU improvement** using adapters with **fewer parameters**. The project will be open-sourced in **January 2025**.
