### ISSUE TITLE
get stuck

### ISSUE THREAD

**Issue by LiewFeng** [kkakkkka/ETRIS#3]
Hi, @kkakkkka , I get stuck with 2 GPU when training. But I can train it successfully with 1 GPU. Do you have any suggestions? Lots of thanks!

Details：I only modify the gpu in the train.sh and gte stuck here.

`File "train.py", line 62, in main                                                                                                                                   
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args, ))                                                                                                  `

**Comment by kkakkkka** [comment]
Hi @LiewFeng, I am awfully sorry for not replying in time. You may be able to solve this problem by checking if the PyTorch version corresponds to the CUDA version.

**Comment by kkakkkka** [comment]
Thanks! I have corrected this part of the code.

**Comment by encounter7777** [comment]
do you solve that problem of how to use multiple gpus to train

**Comment by encounter7777** [comment]
please reply as soon as possible, it helps me a lot

**Comment by kkakkkka** [comment]
> please reply as soon as possible, it helps me a lot

I've noticed your urgent need for multi-GPU training support. I've just implemented this feature, and you can pull the latest code to utilize multi-GPU training.
