### ISSUE TITLE
Training other dataset

### ISSUE THREAD

**Issue by vrk7** [kkakkkka/ETRIS#6]
Hi @zhjohnchan @kkakkkka ,

Could you please let me know how to train this model for a different dataset?

**Comment by kkakkkka** [comment]
Hi there!
Thank you for your interest in our project.
To ensure compatibility, please structure your dataset in the same format as the one we use in our repository. Once you've done that, you can follow the preprocessing steps outlined in the [README](https://github.com/kkakkkka/ETRIS/blob/main/tools/prepare_datasets.md) to prepare your data for training.
