### ISSUE TITLE
Why multiply here?

### ISSUE THREAD

**Issue by thiefjing** [kkakkkka/ETRIS#7]
https://github.com/kkakkkka/ETRIS/blob/78ede06384aa494ac9c55aff6f71f625a443c440/model/layers.py#L342
Excuse me, but could you give some explanation on this line? Generally, the residual connection uses add operation, but why here multiply?

**Comment by Arsiuuu** [comment]
Hi~ Have you resolved it？

**Comment by kkakkkka** [comment]
Yes, residual connections are typically used to facilitate the training of deep networks by adding the input to the output of a layer. This is done to prevent the "vanishing gradient" problem, in which the gradients become too small as they propagate back through many layers, making it difficult for the network to learn.

Multiplication can be applied to certain types of operations. In our approach, the attention mechanism is expected to learn how to prioritize certain parts of the input over others. Multiplication can also be used to represent the interactions between features. Multiplication could be a method to combine these aspects in a non-linear manner, which could capture more complex relationships than simple addition.

We chose multiplication based on preliminary empirical results. We encourage you to experiment with both addition and multiplication in your own implementation to determine which approach yields the best results for your particular dataset and task.
