### ISSUE TITLE
the shape of the 2D attn_mask is torch.Size([17, 17]), but should be (77, 77).

### ISSUE THREAD

**Issue by Z-YuPeng** [kkakkkka/ETRIS#8]
Hi, thanks for your excellent work!
I run your code but got the error following:
The shape of the 2D attn_mask is torch.Size([17, 17]), but should be (77, 77).
How can I solve it ?

**Comment by kkakkkka** [comment]
Hi there,
Thank you for your interest in our project! I am wondering if you have changed the word_len in the config file. If possible, please provide me with some details about the error, including the specific location of the error and possible modifications you may have made to the original code.

**Comment by Z-YuPeng** [comment]
Thanks for your quick response, I modified the word_len from 17 to 77 and it seems to work correctly.
